name: TestK6-N4K

permissions:
  contents: read
  
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chainsaw:
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.22
            version: v1.22.17
        tests:
          - ^deny-force-delete$
    runs-on: ubuntu-latest
    name: ${{ matrix.k8s-version.name }} - ${{ matrix.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ~1.21.1
          cache: false
      - name: Install Tools
        run: |
          set -e
          curl -LO "https://dl.k8s.io/release/${{ matrix.k8s-version.version }}/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Install kind
        shell: bash
        run: |
          set -e
          # For AMD64 / x86_64
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          # For ARM64
          [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create kind cluster
        run: |
          set -e
          kind create cluster --image kindest/node:${{ matrix.k8s-version.version }} --config ./.github/kind.yml
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Install kyverno N4K
        run: |
          set -e
          kubectl create -f https://github.com/nirmata/kyverno/raw/main/config/install-latest-testing.yaml 
          sleep 200
      - name: Install Kyverno Pod Security Enforce policies
        run: |
          set -
          kubectl create -k https://github.com/nirmata/kyverno-policies/pod-security/enforce
          sleep 30          
